### PR TITLE
Development

### PR DESCRIPTION
**Pull request by anaverage-enri**
Finishing sketches for smartphones-shop UI

### CODE REVIEW

**Comment by raksul-sian-izm** [comment]
Do you know what is `.DS_store` ? and do we need to include the file in the repository?

**Comment by anaverage-enri** [comment]
> Do you know what is `.DS_store` ? and do we need to include the file in the repository?


.DS_Store is used to store custom attributes of its containing folder (position of icons, background,...). It's a hidden file and we do not need to include it in the repo. I accidentally added it to the GitHub repo but then got it removed.

**Comment by raksul-sian-izm** [comment]
Yes. You should add `.DS_store`  in `.gitignore`, then it'll be automatically excluded. 

In most of the repositories, like that local dependent files are excluded by `.gitignore`.  e.g. 
https://github.com/raksul/raksul-design/blob/master/.gitignore#L138

**Comment by anaverage-enri** [comment]
Well noted and thank you for the tips!! It was my bad not to include the .gitignore file when initializing the repository.

**Pull request merged**
